FROM golang:1.22.2-alpine AS builder

# default 8080
ARG PORT=8080
ARG GEMINI_API_KEY
ARG POSTGRES_URI
ARG GEMINI_API
ARG GOOGLE_PROJECT_ID
ARG HOST
ARG GOOGLE_ACCESS_TOKEN
ARG RETRIEVE_HISTORY
ARG RELEASE_MODE

WORKDIR /app
COPY . .
RUN go mod download
RUN go build -o ./fbk-go ./main.go


FROM alpine:latest AS runner

ENV PORT=$PORT
ENV GEMINI_API_KEY=$GEMINI_API_KEY
ENV POSTGRES_URI=$POSTGRES_URI
ENV GEMINI_API=$GEMINI_API
ENV GOOGLE_PROJECT_ID=$GOOGLE_PROJECT_ID
ENV HOST=$HOST
ENV GOOGLE_ACCESS_TOKEN=$GOOGLE_ACCESS_TOKEN
ENV RETRIEVE_HISTORY=$RETRIEVE_HISTORY
ENV RELEASE_MODE=$RELEASE_MODE

WORKDIR /app
COPY --from=builder /app/fbk-go .
EXPOSE $PORT
ENTRYPOINT ["./fbk-go"]