FROM golang:1.24.1-alpine AS builder

# default 8080

WORKDIR /app
COPY . .
RUN go mod download
RUN go build -o ./fbk-go ./main.go


FROM alpine:latest AS runner

ARG PORT=8080
ARG GEMINI_API_KEY
ARG POSTGRES_URI
ARG HOST
ARG RETRIEVE_HISTORY
ARG RELEASE_MODE
ARG GEMINI_MODEL

ENV PORT=$PORT
ENV GEMINI_API_KEY=$GEMINI_API_KEY
ENV POSTGRES_URI=$POSTGRES_URI
ENV HOST=$HOST
ENV RETRIEVE_HISTORY=$RETRIEVE_HISTORY
ENV RELEASE_MODE=$RELEASE_MODE
ENV GEMINI_MODEL=$GEMINI_MODEL

WORKDIR /app
COPY --from=builder /app/fbk-go .
EXPOSE $PORT
ENTRYPOINT ["./fbk-go"]