definitions:
  request.History:
    properties:
      answer:
        type: string
      model_source:
        type: string
      question:
        type: string
    required:
    - answer
    - model_source
    - question
    type: object
  request.PromptText:
    properties:
      model:
        type: string
      text:
        type: string
    required:
    - text
    type: object
  request.UpdateHistory:
    properties:
      answer:
        type: string
      id:
        type: integer
      model_source:
        type: string
      question:
        type: string
    required:
    - answer
    - id
    - model_source
    - question
    type: object
info:
  contact: {}
paths:
  /gemini/chat:
    post:
      description: chat action API
      parameters:
      - description: Request Body
        in: body
        name: PromptText
        required: true
        schema:
          $ref: '#/definitions/request.PromptText'
      produces:
      - application/json
      responses: {}
      summary: Chat
      tags:
      - gemini
  /gemini/prompt-text:
    post:
      description: get prompt text result by prompt string
      parameters:
      - description: Request Body
        in: body
        name: PromptText
        required: true
        schema:
          $ref: '#/definitions/request.PromptText'
      produces:
      - application/json
      responses: {}
      summary: Prompt Text
      tags:
      - gemini
  /gemini/reset:
    get:
      description: for resetting all chat session
      produces:
      - application/json
      responses: {}
      summary: Reset chat session
      tags:
      - gemini
  /history/data:
    delete:
      description: delete history data
      parameters:
      - description: history ID to be deleted
        in: query
        name: id
        type: string
      produces:
      - application/json
      responses: {}
      summary: DeleteHistoryData
      tags:
      - history
    patch:
      description: update history data
      parameters:
      - description: Request Body
        in: body
        name: UpdateHistory
        required: true
        schema:
          $ref: '#/definitions/request.UpdateHistory'
      produces:
      - application/json
      responses: {}
      summary: UpdateHistoryData
      tags:
      - history
    post:
      description: create history data
      parameters:
      - description: Request Body
        in: body
        name: CreateGeminiHistory
        required: true
        schema:
          $ref: '#/definitions/request.History'
      produces:
      - application/json
      responses: {}
      summary: CreateHistoryData
      tags:
      - history
  /history/data/{modelSource}:
    get:
      description: get all history data by model source
      parameters:
      - description: Model Source
        in: path
        name: modelSource
        required: true
        type: string
      produces:
      - application/json
      responses: {}
      summary: GetAllHistoryData
      tags:
      - history
  /history/data/bulk:
    post:
      description: create many history data
      parameters:
      - description: Request Body
        in: body
        name: CreateManyGeminiHistory
        required: true
        schema:
          items:
            $ref: '#/definitions/request.History'
          type: array
      produces:
      - application/json
      responses: {}
      summary: CreateManyHistoryData
      tags:
      - history
  /ollama/chat:
    post:
      description: get Ollama chat result by defining the model and message
      parameters:
      - description: Request Body
        in: body
        name: PromptText
        required: true
        schema:
          $ref: '#/definitions/request.PromptText'
      produces:
      - application/json
      responses: {}
      summary: Chat with Ollama Model
      tags:
      - ollama
  /ollama/prompt-text:
    post:
      description: get Ollama prompt text result by defining the model and text
      parameters:
      - description: Request Body
        in: body
        name: PromptText
        required: true
        schema:
          $ref: '#/definitions/request.PromptText'
      produces:
      - application/json
      responses: {}
      summary: Prompt Ollama Text
      tags:
      - ollama
  /ollama/reset:
    get:
      description: reset chat with Ollama model
      produces:
      - application/json
      responses: {}
      summary: Reset Chat with Ollama Model
      tags:
      - ollama
swagger: "2.0"
